### PR TITLE
WIP: changes from fredvd and datakurre improvements.

### PR DESCRIPTION
**Pull request by rnixx**
Keep track of changes and improvements made by @fredvd and @datakurre.

### CODE REVIEW

**Comment by rnixx** [comment]
This PR should be rebased to master and only implement ``search_attrlist`` improvement. Then we can merge

**Comment by fredvd** [comment]
@rnixx What's the issue with the things that were fixed, not to merge them?

**Comment by rnixx** [comment]
@fredvd What fixes are left there except the query normalization?

**Comment by mauritsvanrees** [comment]
As known, this PR is outdated, and cannot be merged in this condition.
I have created a branch https://github.com/zestsoftware/node.ext.ldap/tree/fixes-from-datakurre-and-zest with these changes, so we know the state in which this PR was left. It is the same as the datakurre/master branch.

I will sync our master branch with the original bluedynamics one, and create a fresh branch for Fred's fix 43cc65618917d63248a79154fd70793764805fc5.

You can close this PR, I will create a new one.

**Pull request merged**
