### PR TITLE
Return empty search result list when an LDAP error occurs.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes issue #50.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
cc @rnixx @fredvd

**Comment by rnixx** [comment]
It would be interesting why a subsequent search after an error returns an empty result. Without trying with node.ext.ldap standalone, I guess the problem is somewhere in zope/plone integration.

Anyway I'm fine with catching the error inside the search function and logging a warning. Anyone else with concerns?

**Comment by rnixx** [comment]
No objections? Good to go then.
Thank you!

**Comment by mauritsvanrees** [comment]
Thank you.
This was the last fix I had planned for now, so a new beta release would be handy. But we know how to make an internal release when needed.

**Comment by rnixx** [comment]
https://pypi.org/project/node.ext.ldap/1.0b11/

**Comment by mauritsvanrees** [comment]
Danke!

**Pull request merged**
